# Generated by Django 5.0.6 on 2024-05-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mediaDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('description_task', models.TextField(blank=True)),
                ('supervisor', models.TextField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('condition', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
